import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

const roboto = localFont({
  src: [
    {
      path: "../public/fonts/roboto/Roboto-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/roboto/Roboto-ThinItalic.woff2",
      weight: "100",
      style: "italic",
    },
    {
      path: "../public/fonts/roboto/Roboto-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/roboto/Roboto-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/roboto/Roboto-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/roboto/Roboto-RegularItalic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/roboto/Roboto-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/roboto/Roboto-MediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/roboto/Roboto-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/roboto/Roboto-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/roboto/Roboto-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/roboto/Roboto-BlackItalic.woff2",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-roboto",
  // display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.variable} antialiased`}>{children}</body>
    </html>
  );
}
